add testNG runner
yopeso/skynet-framework-java pull request #20
Opened 2023-04-11 09:30 UTC by aidatulahmad

2023-04-19 07:27 UTC, leonardmustatea requested changes

2023-04-19 07:27 UTC, leonardmustatea commented on src/main/java/skynet/hooks/TestNG/TestNGHooks.java
> +    public void initialize(boolean TestrailPublisher) throws Exception {
Please use Java naming conventions for your params

2023-04-19 07:27 UTC, leonardmustatea commented on src/main/java/skynet/runner/Capabilities.java
> +    public static Serializable get(ITestContext testContext) throws Exception {
Although it's easier to just create a new method for this that does the same thing as another it's still not a good practice. I suggest you use Generics for these changes you have to do now:

```suggestion
    public static <T> Serializable get(T extensionContext) {
```
or even better

```suggestion
    public static <T extends ExtensionContext & ITestContext> Serializable get(T extensionContext) {
```
You'll also have to modify the methods used inside it such as: `setAndroidCaps()` to somethings similar: 

```suggestion
private static <T extends ExtensionContext & ITestContext> UiAutomator2Options setAndroidCaps(T extensionContext) {
```
You can even  change the return type of `get()` method and use Generics instead of Serializable, but I'll leave this up to you since it's not necessary.

Please take in consideration this comment applies to other methods that you are creating/duplicating inside this class

2023-04-19 07:27 UTC, leonardmustatea commented on src/main/java/skynet/runner/WebDriverConfigurator.java
> +    static WebDriver initDriver(ITestContext testContext) throws Exception {
Same as above with Generics for this entire class

2023-04-20 03:44 UTC, aidatulahmad commented on src/main/java/skynet/hooks/TestNG/TestNGHooks.java
> +    public void initialize(boolean TestrailPublisher) throws Exception {
param TestrailPublisher is updated to testrailPublisher

2023-05-09 07:15 UTC, leonardmustatea approved these changes

2023-05-09 07:16 UTC, merged