Aida implementation, fix the publisher take screenshot.
yopeso/skynet-framework-java pull request #24
Opened 2023-05-19 08:26 UTC by cristianmuresan

2023-05-22 05:08 UTC, leonardmustatea requested changes

2023-05-22 05:08 UTC, leonardmustatea commented on src/main/java/skynet/hooks/JUnit5/JUnitHooks.java
> -        if (WebDriverManager.getWebDriver() != null) {
Any particular reason for removing this?
If the driver doesn't quit successfully it throws exceptions in this hook and tear down fails

2023-05-22 05:33 UTC, aidatulahmad commented on src/main/java/skynet/hooks/JUnit5/JUnitHooks.java
> -        if (WebDriverManager.getWebDriver() != null) {
yes, it is because we will need the current driver in TestrailPublisherExtension class which will used to take a screenshot in `afterTestExecution()` for failing test. I also have added the checking `if (driver != null) {
            driver.quit();
        }` in the startDriver() to make sure the driver quit successfully.

2023-05-23 06:40 UTC, leonardmustatea approved these changes

2023-05-23 06:40 UTC, merged